spring.application.name=mfa

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:3399/mfa
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=n+balasubramanya+multi+factor+authentication+project+secret+key
jwt.expiration=3600000